name: workflow1
jobs:
  defaults:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          #repository: PricerAB/cloud-infra-github-runner
          repository: neocycf/repo2
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
