apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: repo1
  annotations:
    github.com/project-slug: neocycf/repo1
    backstage.io/techdocs-ref: dir:.
spec:
  type: production
  lifecycle: service
  owner: team-a
  providesApis:
    - my-api
