apiVersion: v1
kind: Secret
metadata:
  name: gke-eu1
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: gke-eu1
  server: https://gke-eu1.inlets:443
  config: |
    {
      "bearerToken": "aaa123bbb",
       "tlsClientConfig": {
         "insecure": true
       }
    }
