name: workflow1
on:
  push:
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
  # You may pin to the exact commit or the version.
  # uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
    # A repo scoped GitHub Personal Access Token
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
    # The full name of the repository to send the dispatch.
          repository: neocycf/repo2
    # A custom webhook event name.
          event-type: my-event
    # JSON payload with extra information about the webhook event that your action or worklow may use.
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
